aliakspaul/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('thanks/', views.thanks, name='thanks')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aliakspaul.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

aliakspaul/models.py
from email.policy import default
from django.db import models


#HOME PAGE
class Home(models.Model):
    name = models.CharField(max_length=30)
    greeting_1 = models.CharField(max_length=10)
    greeting_2 = models.CharField(max_length=10)
    picture = models.ImageField(upload_to='picture/')

    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


#ABOUT PAGE
class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=50)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')
    email = models.EmailField(max_length=70, blank=True, unique=True, default='-')
    phone = models.CharField(max_length=200, default='-')
    adress = models.CharField(max_length=200, default='-')
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.career


class Profile(models.Model):
    about = models.ForeignKey(About, on_delete=models.CASCADE)
    social_name = models.CharField(max_length=10)
    link = models.URLField(max_length=200)


#SKILLS PAGE
class Category(models.Model):
    name = models.CharField(max_length=20)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self) :
        return self.name


class Skills(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=50)


#Portfolio page
class Portfolio(models.Model):
    name = models.CharField(max_length=20, default="Portfolio")
    image = models.ImageField(upload_to='portfolio/')
    link = models.URLField(max_length=200)
 
    def __str__(self) :
        return f'Portfolio{self.id}'

aliakspaul/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'contact__input', 'placeholder': 'Name'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'contact__input', 'placeholder': 'Email'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'contact__input',  'placeholder': '...'}))

aliakspaul/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from .models import *
from .forms import ContactForm
from django.template.loader import render_to_string

def index(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            html = render_to_string('contactform.html', {
                'name': name, 
                'email': email,
                'message': message,
            })
             
            send_mail(name, 
                    message, 
                    email, 
                    ['paulouskaya.aliaksandra@gmail.com'], 
                    html_message=html)

            return redirect('/thanks/')
    else:
        form = ContactForm()

    
    home = Home.objects.latest('updated')
    about = About.objects.latest('updated')
    profile = Profile.objects.filter(about=about)
    categories = Category.objects.all()
    portfolios = Portfolio.objects.all()

    context = {
        'home': home,
        'about': about,
        'profile': profile,
        'categories': categories,
        'portfolios': portfolios,
        'form': form, 
    }
    
    return render(request, 'index.html', context)


def thanks(request):
    return render(request, 'thanks.html')

aliakspaul/templates/contactform.html
<h2>Contact form submission</h2>
<p><b>Name:</b> {{ name }}  </p>
<p><b>Email:</b> {{ email }}  </p>
<p><b>Message:</b> {{ message }}  </p> 

aliakspaul/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}" >

    <!-- Box Icons https://boxicons.com/ -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <title>Portfolio</title>
</head>
<body> 
    <!-- Header -->
    <header class="l-header">
        <nav class="nav bd-grid">
            <div> 
                <a href="#" class="nav__logo">{{ home.name }}</a>
            </div>

            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list">
                    <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                    <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                    <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                    <li class="nav__item"><a href="#portfolio" class="nav__link">Portfolio</a></li>
                    <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                </ul>
            </div>
            
            <div class="nav__toggle" id="nav-toggle">
                <i class='bx bx-menu'></i>
            </div>
        </nav>
    </header>
    <main class="l-main">
        <!-- Home  -->
        <section class="home" id="home">
            <div class="home__container bd-grid"> 
                <h1 class="home__title"><span>{{ home.greeting_1 }}</span><br>{{ home.greeting_2 }}</h1>

                <div class="home__scroll">
                    <a href="#about" class="home__scroll-link"><i class='bx bxs-up-arrow-alt'></i>Scroll down</a>
                </div>

                <img src="{{ home.picture.url  }}" alt="" class="home__img">
            </div>
        </section>
        
        <!-- About -->
        <section class="about section" id="about">

            <h2 class="section-title">About</h2>

            <div class="about__container bd-grid">
                <div class="about__img"> 
                    <img src="{{ about.profile_img.url }}" alt="">
                </div>
                <div>
                    <h2 class="about__subtitle">{{ about.heading }}</h2>
                    <span class="about__professional">{{ about.career  }}</span>
                    <p class="about__text">{{ about.description  }}</p>
                </div>

                <div class="about__social">
                    <a href="https://www.linkedin.com/in/paulouskaya/" class="about__social-icon"><i class='bx bxl-linkedin'></i></a>
                    <a href="https://github.com/AliaksPaul/" class="about__social-icon"><i class='bx bxl-github'></i></a>
                    <a href="https://www.behance.net/alexandpavlovsç" class="about__social-icon"><i class='bx bxl-behance' ></i></a>
                </div>
            </div>
        </section>

        <!-- Skills -->
        <section class="skills section" id="skills">
            <h2 class="section-title">Skills</h2> 

            <div class="skills__container bd-grid">
                <div class="skills_box">

                    {% for category in categories %}
                        <h3 class="skills__subtitle">{{ category.name }}</h3>

                        {% for skills in category.skills_set.all %}
                            <span class="skills__name">{{ skills.skill_name }}</span>
                        {% endfor%}
                            
                    {% endfor%}  

                </div>
                <div class="skills__img">
                    <img src="{% static 'assets/img/skills.jpeg' %}" alt="">
                </div>
            </div>
        </section>

        <!-- Portfolio -->
        <section class="portfolio section" id="portfolio">
            <h2 class="section-title">Portfolio</h2> 

            <div class="portfolio__container bd-grid">
            {% for portfolio in portfolios %}
                <div class="portfolio__img">
                    <img src="{{ portfolio.image.url }}" alt="">

                    <div class="portfolio__link">
                        <a href="{{ portfolio.link }}" class="portfolio__link-name">{{ portfolio.name }}s</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>

        <!-- Contact -->
        <section class="contact section" id="contact">
            <h2 class="section-title" id="contact">Contact</h2> 

            <div class="contact__container bd-grid">

                <div class="contact__info">
                    <h3 class="contact__subtitle">EMAIL</h3>
                    <span class="contact__text">{{ about.email }}</span>

                    <h3 class="contact__subtitle">PHONE</h3>
                    <span class="contact__text">{{ about.phone }}</span>
 
                    <h3 class="contact__subtitle">ADRESS</h3>
                    <span class="contact__text">{{ about.adress }}</span>
                </div>

                <div class="contact__info">
                    <form method="post" class="contact__form" action=".">
                        {% csrf_token %}
                        <div class="contact__inputs" >
                        {{ form.name }}
                        {{ form.email }}
                        </div>
                        {{ form.message }}
                        <button type="submit" class="contact__button">Submit</button>
                    </form>
                </div> 

            </div>
        </section>
    </main>

    <!-- Footer -->
    <footer class="footer section">
        <div class="footer__container bd-grid">
            <div class="footer__data">
                <h2 class="footer__title">ALIAKS PAUL</h2>
                <p class="footer_text">I am Aliaks Puaul and this is my personal Website</p>
            </div>
            <div class="footer__data">
                <h2 class="footer__title">EXPLORE</h2>
                <ul>
                    <li>
                        <a href="#home" class="footer__link">Home</a> 
                        <a href="#about" class="footer__link">About</a> 
                        <a href="#skills" class="footer__link">Skills</a>
                        <a href="#portfolio" class="footer__link">Portfolio</a>
                        <a href="#contact" class="footer__link">Contact</a>
                    </li>
                </ul>
            </div>
            <div class="footer__data">
                <h2 class="footer__title">FOLLOW</h2>
                <a href="instagram.com/aliaks.paul" class="footer__social"><i class='bx bxl-instagram'></i></a>
                <a href="#facebook" class="footer__social"><i class='bx bxl-meta'></i></a>
                <a href="#twitter" class="footer__social"><i class='bx bxl-twitter'></i></a>
            </div>
        </div>

    </footer>
    <!-- Scroll Reveal https://scrollrevealjs.org/ -->
    <script src="https://unpkg.com/scrollreveal"></script> 

    <!-- Main JS -->
        <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>

aliakspaul/templates/thanks.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}" >

    <!-- Box Icons https://boxicons.com/ -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <title>Thanks</title>
</head>

    <header class="l-header">
        <nav class="nav bd-grid">
        </nav>
    </header>
    <main class="l-main">
        <section class="home" id="home">
            <br>
            <div class="home__container bd-grid"> 
                <h2 class="thank__title"> Thank you!<br><span> I've recieved your Email and will respond you shortly...</span>
                    <br><a href="/" class="thank__title"><span> Back to the Home Page</span><i class='bx bx-right-arrow-alt'></i></a>
                </h2>   
            </div>
        </section>
    </main>